---
galaxy_info:
  author: alisonlhart
  description: GitHub MCP role - builds GitHub MCP server from source
  license: MIT
  min_ansible_version: '2.18'
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  - role: common
