---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create mcpservers.json file
      ansible.builtin.include_role:
        name: ansible.mcp_builder.common
        tasks_from: generate_manifest.yml

    - name: Create mcpmanage script
      ansible.builtin.include_role:
        name: ansible.mcp_builder.common
        tasks_from: generate_management.yml
