---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
        - --inventory=/path/to/inventory.yml
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          common_mcp_base_path: "/tmp/mcp_manifest"
          common_discovered_registries:
            - name: mcp_one
              type: stdio
              path: /path/to/mcp/one
              args:
                - "--stdio"
            - name: mcp_two
              type: http
              path: "https://path.to/mcp/two"
