---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest

dependencies:
  system: |
  python: |

options:
  package_manager_path: /usr/bin/microdnf

# additional_build_files:

# additional_build_steps:
#   prepend_base:


#   append_final:
