---
name: mcp_builder
namespace: ansible
version: 0.0.3

readme: README.md
description: Ansible collection for installing MCP (Model Context Protocol) servers into execution environments. **Technology Preview**

authors:
  - Alison Hart (@alisonlhart)
  - Kate Case (@Qalthos)

license_file: LICENSE

repository: https://github.com/redhat-cop/mcp_builder

issues: https://github.com/redhat-cop/mcp_builder/issues

tags: [ai, tools, mcp]

build_ignore:
  - .ansible/
  - .github/
  - .pre-commit-config.yaml
  - .prettierignore
  - tools/

# dependencies:
#   "ansible.mcp": ">=1.0.0"
