---
name: mcp_builder
namespace: ansible
version: 1.0.0

readme: README.md
description: Ansible collection for installing MCP (Model Context Protocol) servers into execution environments. **Technology Preview**

authors:
  - Alison Hart (@alisonlhart)
  - Kate Case (@Qalthos)

license_file: LICENSE

repository: https://github.com/ansible/mcp_builder

issues: https://github.com/ansible/mcp_builder/issues

tags: [ai, tools, mcp]

build_ignore:
  - .ansible/
  - .github/
  - Containerfile

# dependencies:
#   "ansible.mcp": ">=1.0.0"
