---
- name: Generate portal template files
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    mcp_roles:
      - github_mcp

  tasks:
    - name: Load MCP roles to gain access to defaults
      ansible.builtin.include_role:
        name: "{{ item }}"
        tasks_from: noop
        public: true
      loop: "{{ mcp_roles }}"

    - name: Zip registry with details
      ansible.builtin.set_fact:
        registries: >-
          {{ registries | default([]) | union([{
            'name': item,
            'registry': lookup('vars', item + '_registry') | zip(lookup('vars', item + '_build_details')),
          }]) }}
        mcp_extension_dir: "{{ playbook_dir }}/extensions/mcp"
      loop: "{{ mcp_roles }}"

    - name: Create destination directories
      ansible.builtin.file:
        dest: "{{ mcp_extension_dir }}/{{ item.name }}"
        state: directory
        mode: "0755"
      loop: "{{ registries }}"

    - name: Template each registry
      ansible.builtin.template:
        src: server.yaml.j2
        dest: "{{ mcp_extension_dir }}/{{ item[0].name }}/{{ item[1][0].name }}.yaml"
        mode: "0644"
        lstrip_blocks: true
      loop: "{{ registries | subelements('registry') }}"
