---
# Default variables for common role
# Users can override these in their playbooks or group_vars

# Base path for MCP installations
common_mcp_base_path: "/opt/mcp"

# Go version to install
common_golang_version: "1.24.4"

# Common MCP Server Registry - Add extra entries here that aren't defined in other roles
# common_mcp_registry:

# System paths
common_system_bin_path: "/usr/local/bin"

# External URLs
common_uv_installer_url: "https://astral.sh/uv/install.sh"
