---
# Prepare playbook - Install the collection in the test container
# Collections are installed via dependency phase (requirements.yml)
# This playbook just installs our collection and sets up paths
- name: Prepare test environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure collection directory exists
      ansible.builtin.file:
        path: /tmp/ansible_collections/ansible
        state: directory
        mode: "0755"

    - name: Copy collection to target location
      ansible.builtin.copy:
        src: /workspace/
        dest: /tmp/ansible_collections/ansible/mcp_builder
        remote_src: true
        mode: "0755"
      register: collection_copy

    - name: Verify collection is installed
      ansible.builtin.stat:
        path: /tmp/ansible_collections/ansible/mcp_builder
      register: collection_check

    - name: Verify collection structure
      ansible.builtin.shell: |
        set -o pipefail
        ls -la /tmp/ansible_collections/ansible/mcp_builder/ | head -10
        test -f /tmp/ansible_collections/ansible/mcp_builder/galaxy.yml && echo "galaxy.yml found" || echo "galaxy.yml NOT found"
      register: collection_structure
      changed_when: false

    - name: Display collection structure
      ansible.builtin.debug:
        var: collection_structure.stdout_lines

    - name: Fail if collection not found
      ansible.builtin.fail:
        msg: "Collection not installed at /tmp/ansible_collections/ansible/mcp_builder"
      when: not collection_check.stat.exists

    - name: Set ANSIBLE_COLLECTIONS_PATH
      ansible.builtin.set_fact:
        ansible_collections_paths: ["/tmp/ansible_collections"]
