---
# Prepare playbook - Install the collection in the test container

- name: Prepare test environment
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure molecule-plugins[podman] is installed
      ansible.builtin.pip:
        name: molecule-plugins[podman]
        state: present
      become: true
      failed_when: false
    - name: Detect collection root
      ansible.builtin.set_fact:
        molecule_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | default('') }}"
        github_workspace: "{{ lookup('env', 'GITHUB_WORKSPACE') | default('') }}"

    - name: Set collection root based on detected paths
      ansible.builtin.set_fact:
        collection_root: >-
          {%- if ansible_connection == 'podman' or ansible_connection == 'docker' -%}
            /workspace/ansible.mcp_builder
          {%- elif molecule_dir and molecule_dir.endswith('/extensions') -%}
            {{ molecule_dir | dirname }}
          {%- elif molecule_dir -%}
            {{ molecule_dir }}
          {%- elif github_workspace -%}
            {{ github_workspace }}
          {%- else -%}
            {{ playbook_dir }}/../..
          {%- endif -%}

    - name: Ensure galaxy.yml exists
      ansible.builtin.stat:
        path: "{{ collection_root }}/galaxy.yml"
      register: galaxy_yml_check

    - name: Fail if galaxy.yml missing
      ansible.builtin.fail:
        msg: "galaxy.yml not found at {{ collection_root }}. MOLECULE_PROJECT_DIRECTORY={{ molecule_dir }}, GITHUB_WORKSPACE={{ github_workspace }}"
      when: not galaxy_yml_check.stat.exists

    - name: Ensure collection directory exists
      ansible.builtin.file:
        path: /tmp/ansible_collections/ansible
        state: directory
        mode: "0755"

    - name: Copy collection to target location
      ansible.builtin.copy:
        src: "{{ collection_root }}/"
        dest: /tmp/ansible_collections/ansible/mcp_builder
        remote_src: true
        mode: "0755"
      register: collection_copy

    - name: Verify collection is installed
      ansible.builtin.stat:
        path: /tmp/ansible_collections/ansible/mcp_builder
      register: collection_check

    - name: Fail if collection not found
      ansible.builtin.fail:
        msg: "Collection not installed at /tmp/ansible_collections/ansible/mcp_builder"
      when: not collection_check.stat.exists
